// Generates THIRD_PARTY_NOTICES.md from the components that actually ship in
// the application binary:
//   * npm production dependencies bundled into the UI (incl. fonts);
//   * Rust crates linked into the Windows executable (normal dependencies only,
//     no build/dev dependencies, no proc-macro crates).
// License texts are copied from each package; identical texts are printed once.
//
// Usage (from repo root): node dev/scripts/third-party.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const app = path.join(root, 'dev', 'app');
const out = path.join(root, 'THIRD_PARTY_NOTICES.md');
const LICENSE_FILE = /^(licen[cs]e|copying|notice)([-._].*)?(\.(md|txt))?$/i;

function licenseTexts(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => LICENSE_FILE.test(f) && fs.statSync(path.join(dir, f)).isFile())
    .sort()
    .map((f) => fs.readFileSync(path.join(dir, f), 'utf8').replace(/\r\n/g, '\n').trim());
}

// ---------- npm ----------
function npmComponents() {
  const pkg = JSON.parse(fs.readFileSync(path.join(app, 'package.json'), 'utf8'));
  const seen = new Map();
  const visit = (name) => {
    if (seen.has(name)) return;
    const dir = path.join(app, 'node_modules', name);
    const pj = path.join(dir, 'package.json');
    if (!fs.existsSync(pj)) return;
    const p = JSON.parse(fs.readFileSync(pj, 'utf8'));
    seen.set(name, {
      name,
      version: p.version,
      license: typeof p.license === 'string' ? p.license : p.license?.type ?? 'see text',
      url: (typeof p.repository === 'string' ? p.repository : p.repository?.url ?? p.homepage ?? '').replace(/^git\+/, '').replace(/\.git$/, ''),
      texts: licenseTexts(dir),
    });
    for (const d of Object.keys(p.dependencies ?? {})) visit(d);
  };
  for (const d of Object.keys(pkg.dependencies ?? {})) visit(d);
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}

// ---------- cargo ----------
function cargoComponents() {
  const meta = JSON.parse(
    execFileSync('cargo', ['metadata', '--format-version', '1', '--locked', '--filter-platform', 'x86_64-pc-windows-msvc'], {
      cwd: path.join(app, 'src-tauri'),
      maxBuffer: 256 * 1024 * 1024,
    }).toString('utf8'),
  );
  const pkgs = new Map(meta.packages.map((p) => [p.id, p]));
  const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
  const rootId = meta.resolve.root;
  const linked = new Set();
  const stack = [rootId];
  while (stack.length) {
    const id = stack.pop();
    if (linked.has(id)) continue;
    linked.add(id);
    for (const dep of nodes.get(id)?.deps ?? []) {
      const normal = dep.dep_kinds.some((k) => k.kind === null);
      const target = pkgs.get(dep.pkg);
      const procMacro = target?.targets.some((t) => t.kind.includes('proc-macro'));
      if (normal && !procMacro) stack.push(dep.pkg);
    }
  }
  linked.delete(rootId);
  return [...linked]
    .map((id) => pkgs.get(id))
    .map((p) => ({
      name: p.name,
      version: p.version,
      license: p.license ?? (p.license_file ? 'see text' : 'unknown'),
      url: p.repository ?? p.homepage ?? `https://crates.io/crates/${p.name}`,
      texts: licenseTexts(path.dirname(p.manifest_path)),
    }))
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

function render(npm, cargo) {
  const all = [...npm, ...cargo];
  const textIds = new Map();
  const ref = (c) =>
    c.texts.map((t) => {
      if (!textIds.has(t)) textIds.set(t, textIds.size + 1);
      return `[L${textIds.get(t)}](#l${textIds.get(t)})`;
    });
  const row = (c) => `| ${c.name} | ${c.version} | ${c.license} | ${ref(c).join(' ') || '—'} |`;
  const lines = [
    '# Third-party notices',
    '',
    'MDVibe includes the open-source components listed below. Each remains under its own license;',
    'the license texts follow the tables. This file is generated by `dev/scripts/third-party.mjs`.',
    '',
    `Components: ${npm.length} bundled into the user interface, ${cargo.length} linked into the Windows executable.`,
    '',
    'The Microsoft Edge WebView2 Runtime is not distributed with MDVibe; it is provided by Windows',
    'or installed by Microsoft\'s bootstrapper under Microsoft\'s own terms.',
    '',
    '## User interface (JavaScript, fonts)',
    '',
    '| Component | Version | License | Text |',
    '| --- | --- | --- | --- |',
    ...npm.map(row),
    '',
    '## Application shell (Rust crates)',
    '',
    '| Component | Version | License | Text |',
    '| --- | --- | --- | --- |',
    ...cargo.map(row),
    '',
    '## License texts',
    '',
  ];
  for (const [text, id] of textIds) {
    const users = all.filter((c) => c.texts.includes(text)).map((c) => c.name);
    const uniq = [...new Set(users)];
    lines.push(`### L${id}`, '', `Used by: ${uniq.join(', ')}`, '', '```text', text.replace(/```/g, "'''"), '```', '');
  }
  const missing = all.filter((c) => !c.texts.length).map((c) => `${c.name}@${c.version} (${c.license})`);
  if (missing.length) {
    lines.push('## Components without a bundled license file', '', 'These packages declare the license above but ship no license text; the standard text of that license applies.', '');
    lines.push(...missing.map((m) => `- ${m}`), '');
  }
  return lines.join('\n');
}

const npm = npmComponents();
const cargo = cargoComponents();
const md = render(npm, cargo);
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (cur !== md) {
    console.error('THIRD_PARTY_NOTICES.md is out of date: run node dev/scripts/third-party.mjs');
    process.exit(1);
  }
  console.log('THIRD_PARTY_NOTICES.md is up to date.');
} else {
  fs.writeFileSync(out, md);
  console.log(`wrote THIRD_PARTY_NOTICES.md: ${npm.length} npm + ${cargo.length} crates`);
}
